
const products=window.NOVA_PRODUCTS||[];
const money=n=>`AED ${Number(n).toFixed(0)}`;
const cartKey="novaCart", wishKey="novaWishlist";
const getCart=()=>JSON.parse(localStorage.getItem(cartKey)||"[]");
const saveCart=c=>{localStorage.setItem(cartKey,JSON.stringify(c));updateCartCount();};
const getWish=()=>JSON.parse(localStorage.getItem(wishKey)||"[]");
const saveWish=w=>localStorage.setItem(wishKey,JSON.stringify(w));
const findProduct=id=>products.find(p=>p.id===Number(id));
function updateCartCount(){let n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll(".cart-count").forEach(x=>x.textContent=n)}
function toast(msg){let t=document.querySelector(".toast");if(!t)return;t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function addToCart(id,size=null,color=null){const p=findProduct(id);if(!p)return;size=size||p.sizes[0];color=color||p.colors[0];let c=getCart(),x=c.find(i=>i.id===p.id&&i.size===size&&i.color===color);x?x.qty++:c.push({id:p.id,qty:1,size,color});saveCart(c);toast(`${p.name} added to bag`)}
function toggleWish(id,btn){let w=getWish();id=Number(id);w.includes(id)?w=w.filter(x=>x!==id):w.push(id);saveWish(w);btn.classList.toggle("active",w.includes(id));btn.textContent=w.includes(id)?"♥":"♡";toast(w.includes(id)?"Added to wishlist":"Removed from wishlist")}
function productCard(p){let sale=p.old?`<span class="badge">${Math.round((1-p.price/p.old)*100)}% OFF</span>`:"";return `<article class="product-card" data-id="${p.id}"><div class="product-img">${sale}<button class="wish ${getWish().includes(p.id)?"active":""}" onclick="toggleWish(${p.id},this)">${getWish().includes(p.id)?"♥":"♡"}</button></div><div class="product-info"><h3>${p.name}</h3><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><div class="quick-actions"><button class="smallbtn quick" onclick="quickView(${p.id})">Quick View</button><button class="smallbtn dark" onclick="addToCart(${p.id})">Add to Bag</button></div></div></article>`}
function renderProducts(selector,list){let el=document.querySelector(selector);if(el)el.innerHTML=list.map(productCard).join("")}
function quickView(id){let p=findProduct(id),m=document.querySelector("#quickModal");if(!m)return;m.querySelector(".modal-content").innerHTML=`<div class="product-detail"><div class="gallery-main">${p.name.split(" ")[0]}</div><div class="detail"><p class="eyebrow">NOVA UAE</p><h2>${p.name}</h2><h3>${money(p.price)}</h3><p class="muted">Contemporary design made for life in the UAE. Easy styling, considered details and a polished finish.</p><button class="btn" onclick="addToCart(${p.id});closeModal()">ADD TO BAG</button> <a class="btn" href="product.html?id=${p.id}">VIEW PRODUCT</a></div></div>`;m.classList.add("show")}
function closeModal(){document.querySelectorAll(".modal").forEach(m=>m.classList.remove("show"))}
function initHeader(){document.querySelector(".hamb")?.addEventListener("click",()=>document.querySelector(".nav")?.classList.toggle("mobile-open"));updateCartCount()}
function initAccordions(){document.querySelectorAll(".acc button").forEach(b=>b.addEventListener("click",()=>b.parentElement.classList.toggle("open")))}
function initNewsletter(){document.querySelectorAll(".newsletter form").forEach(f=>f.addEventListener("submit",e=>{e.preventDefault();let i=f.querySelector("input");if(!i.value||!i.checkValidity()){i.reportValidity();return}f.outerHTML='<p class="success">Welcome to NOVA UAE! Your 10% offer is on its way.</p>'}))}
function initContact(){document.querySelector("#contactForm")?.addEventListener("submit",e=>{e.preventDefault();let f=e.currentTarget;if(!f.checkValidity()){f.reportValidity();return}document.querySelector("#contactSuccess").textContent="Thanks for reaching out. The NOVA UAE team will get back to you soon.";f.reset()})}
function initSearch(){let input=document.querySelector("#siteSearch");input?.addEventListener("input",()=>{let q=input.value.toLowerCase(),list=products.filter(p=>(p.name+" "+p.cat).toLowerCase().includes(q));renderProducts("#searchResults",list)})}
function initShop(){let grid=document.querySelector("#shopGrid");if(!grid)return;let state={cat:"",size:"",color:"",max:400,sort:"recommended"};function apply(){let a=products.filter(p=>(!state.cat||p.cat===state.cat)&&(!state.size||p.sizes.includes(state.size))&&(!state.color||p.colors.includes(state.color))&&p.price<=state.max);if(state.sort==="low")a.sort((x,y)=>x.price-y.price);if(state.sort==="high")a.sort((x,y)=>y.price-x.price);if(state.sort==="new")a.sort((x,y)=>Number(y.new)-Number(x.new));renderProducts("#shopGrid",a);document.querySelector("#productCount").textContent=`${a.length} products`}document.querySelectorAll("[data-cat]").forEach(x=>x.addEventListener("click",()=>{state.cat=x.dataset.cat;apply()}));document.querySelectorAll("[data-size]").forEach(x=>x.addEventListener("click",()=>{state.size=x.dataset.size;apply()}));document.querySelectorAll("[data-color]").forEach(x=>x.addEventListener("click",()=>{state.color=x.dataset.color;apply()}));document.querySelector("#priceRange")?.addEventListener("input",e=>{state.max=+e.target.value;document.querySelector("#priceValue").textContent=money(state.max);apply()});document.querySelector("#sort")?.addEventListener("change",e=>{state.sort=e.target.value;apply()});apply()}
function initProduct(){let id=new URLSearchParams(location.search).get("id")||1,p=findProduct(id);if(!p)return;document.querySelectorAll("[data-product-name]").forEach(x=>x.textContent=p.name);document.querySelector("#detailPrice").textContent=money(p.price);document.querySelector("#detailOld")?.replaceChildren(p.old?document.createTextNode(money(p.old)):"");document.querySelector("#detailDesc").textContent=`A sophisticated ${p.name.toLowerCase()} designed for elegant days, dinners and special occasions across the UAE.`;let sw=document.querySelector("#colors");sw.innerHTML=p.colors.map((c,i)=>`<button class="swatch ${i===0?"selected":""}" onclick="selectOption(this)">${c}</button>`).join("");let sz=document.querySelector("#sizes");sz.innerHTML=p.sizes.map((s,i)=>`<button class="size ${i===0?"selected":""}" onclick="selectOption(this)">${s}</button>`).join("");document.querySelector("#addDetail")?.addEventListener("click",()=>{addToCart(p.id,document.querySelector(".size.selected")?.textContent,document.querySelector(".swatch.selected")?.textContent)});document.querySelector("#buyNow")?.addEventListener("click",()=>{addToCart(p.id);location.href="cart.html"})}
function selectOption(el){el.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));el.classList.add("selected")}
function initCart(){let box=document.querySelector("#cartItems");if(!box)return;function render(){let c=getCart();if(!c.length){box.innerHTML='<div class="feature"><h3>Your bag is empty</h3><p class="muted">Discover new styles and add your favourites to your bag.</p><a class="btn" href="shop.html">SHOP NOW</a></div>';document.querySelector("#subtotal").textContent=money(0);document.querySelector("#delivery").textContent="FREE";document.querySelector("#total").textContent=money(0);return}box.innerHTML=c.map((i,idx)=>{let p=findProduct(i.id);return `<div class="cart-item"><div class="cart-thumb"></div><div><b>${p.name}</b><p class="muted">${i.color} · ${i.size}</p><div class="qty"><button onclick="changeQty(${idx},-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${idx},1)">+</button></div><button class="smallbtn" onclick="removeCart(${idx})" style="margin-top:8px">Remove</button></div><strong>${money(p.price*i.qty)}</strong></div>`}).join("");let sub=c.reduce((s,i)=>s+findProduct(i.id).price*i.qty,0);document.querySelector("#subtotal").textContent=money(sub);document.querySelector("#delivery").textContent=sub>=199?"FREE":money(20);document.querySelector("#total").textContent=money(sub>=199?sub:sub+20)}window.changeQty=(idx,d)=>{let c=getCart();c[idx].qty+=d;if(c[idx].qty<1)c.splice(idx,1);saveCart(c);render()};window.removeCart=idx=>{let c=getCart();c.splice(idx,1);saveCart(c);render()};render()}
document.addEventListener("DOMContentLoaded",()=>{initHeader();initAccordions();initNewsletter();initContact();initSearch();initShop();initProduct();initCart();document.querySelectorAll("[data-scroll]").forEach(x=>x.addEventListener("click",e=>{e.preventDefault();document.querySelector(x.dataset.scroll)?.scrollIntoView({behavior:"smooth"})}));document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal()})});
